services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: cse2430-image
    stdin_open: true
    tty: true
    working_dir: /home/assignments
    volumes:
      - ./:/home/assignments
    command: bash
